### ISSUE TITLE
Design a new logo

### ISSUE THREAD

**Issue by gauthamzz** [aviary-apps/Pelican#16]
Facebook told us to change the logo and a new logo is to be added.

**Comment by Sweta271097** [comment]
Hello, 

Can I get an idea about how do you want the logo to look like?

**Comment by gauthamzz** [comment]
It should be clean and minimal, maybe some gradients. But honestly only thing that matters is that its not taken from some website and looks good.

**Comment by Sweta271097** [comment]
Okay, I'm on it.

**Comment by imbipulkumar** [comment]
Hey @gauthamzz , I believe that small letter f (ie. fb icon) with pelican head which I see[ here](https://lh3.googleusercontent.com/jnjenqKeyHk3rK0RayWF-3Eqky1Q7jAzM2yG21N-lNlPGZnyeaIcAJhZDj8vkeHB2mwc2wTRmVg=w640-h400-e365) is best for this app. As it implies facebook's icon and the pelican.
![fbpelican](https://user-images.githubusercontent.com/31007652/50087664-d5c54980-0226-11e9-9562-7231fe2fa1fb.PNG)

**Comment by gauthamzz** [comment]
That was the previous logo , fb send legal notice to remove it 😔

It breaks their policy. Hence we can’t use that anyway

**Comment by imbipulkumar** [comment]
Hello @gauthamzz , check this new icon  I have designed and edited. I have spent my whole day in making it so kindly approve this for Pelican icon.
PS.: I think fb will have no issue in this.
![icon](https://user-images.githubusercontent.com/31007652/50215406-ebfb1300-03a8-11e9-88a8-016999550c20.png)

**Comment by gauthamzz** [comment]
I have no problem adding this. But i think this also violates fb's policy. https://developers.facebook.com/docs/apps/review/submission-guidelines

**Comment by gauthamzz** [comment]
They will end up sending me legal notice and take the app down. If you can remove fb icon and put something else, it would be fine.

**Comment by imbipulkumar** [comment]
> They will end up sending me legal notice and take the app down. If you can remove fb icon and put something else, it would be fine.
> 
> If you want a suggestion, a logo which looks like any emoji would be good. But ultimately it is your choice. Just don't violate the policy by fb.

OK I will keep it in my mind.

**Comment by Sweta271097** [comment]
@gauthamzz I made a new logo with procreate which is colorful and peppy and won't break fb's policy. The beak of the pelican acts a P here. If you like it, I'll make a PR.
![pelican](https://user-images.githubusercontent.com/32592225/50234917-bec85800-03dc-11e9-8df5-0a05d91f401f.PNG)

**Comment by gauthamzz** [comment]
It looks too flashy, can you reduce the red tone a bit. 

I wanna give a one-two day time frame if anyone else wants to suggest another logo. As this is a major change. I hope you understand. 

After which if there is no change then update 

1. Readme
2. Popup 
3. upload logo in the dimensions required by the chrome webstore. (with and without bg)

**Comment by Sweta271097** [comment]
@gauthamzz Yes, I can reduce the red tone. I can also make the logo in some other color combination if you would like me to.

**Comment by gauthamzz** [comment]
Yes that would be great. I like minimal logos. This looks too complicated for being on top of a bar. Since it will be only on top of the task bar. It would be hard to make a visible change using the current logo you suggested. You dont really have to make a word out of the name. You can just use a simple design.

If you tone the colour variation a bit and make it stand straight. I think this can be a really good logo.

If you want inspiration do look at noun project https://thenounproject.com/

**Comment by Sweta271097** [comment]
@gauthamzz This time I made a simple and minimal line art logo depicting a pelican. It's almost like an icon. Hope you like it this time, I have kept the color of the logo the same as Facebook's logo. If you approve it, I'll make a PR.
![logo pelican](https://user-images.githubusercontent.com/32592225/50242190-9564f780-03ef-11e9-998c-fc020dfe4915.png)

**Comment by gauthamzz** [comment]
Can you send one more image with no bg. If you dont mind. If you can come to gitter channel, i can help you out with faster feedback!

**Comment by Sweta271097** [comment]
@gauthamzz 
![screenshot 56](https://user-images.githubusercontent.com/32592225/50242443-5e431600-03f0-11e9-941c-6b8c6d3e4bcb.png)

**Comment by gauthamzz** [comment]
I guess the earlier one is better tbh. 
Can you make logos fit in a square shape. It looks too much rectangular.

**Comment by Sweta271097** [comment]
@gauthamzz  Earlier one as in? The pink and blue one?

**Comment by gauthamzz** [comment]
Yes this looks good. You can use this and change everything

**Comment by Sweta271097** [comment]
@gauthamzz Okay, so I am making a PR.

**Comment by gauthamzz** [comment]
I was sleeping 😅 just merged
